"""add rooms and timetable

Revision ID: e6a5a4ff7064
Revises: 404390028518
Create Date: 2026-09-03 23:05:57.934954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a5a4ff7064'
down_revision: Union[str, Sequence[str], None] = '404390028518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('room_type', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('is_lab', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_college_id'), 'rooms', ['college_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('timetable_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_college_id'), 'timetables', ['college_id'], unique=False)
    op.create_index(op.f('ix_timetables_day_of_week'), 'timetables', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index(op.f('ix_timetables_room_id'), 'timetables', ['room_id'], unique=False)
    op.create_index(op.f('ix_timetables_section_id'), 'timetables', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetables_subject_id'), 'timetables', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetables_teacher_id'), 'timetables', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetables_teacher_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_subject_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_section_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_room_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_day_of_week'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_college_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_college_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
